[build]
  base = "."
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
